version: '3'

services:
  fluentd-elasticsearch:
    image: registry.admicro.vn/common/fluentd-es:v1.6
    volumes:
      - ./etc:/fluentd/etc
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"
    ports:
      - "24224:24224"
    environment:
      - FLUENTD_CONF=fluentd.conf
